name: Release

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * 4"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build geoip
        id: build
        run: go run -v .

      - name: Generate sha256 hash
        if: steps.build.outputs.skip != 'true'
        run: |
          sha256sum geoip.db > geoip.db.sha256sum
          sha256sum geoip-cn.db > geoip-cn.db.sha256sum

      - uses: dev-drprasad/delete-older-releases@v0.3.2
        with:
          keep_latest: 3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a release
        if: steps.build.outputs.skip != 'true'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.build.outputs.tagName }}
          release_name: ${{ steps.build.outputs.tagName }}
          draft: false
          prerelease: false

      - name: Release geoip.db
        if: steps.build.outputs.skip != 'true'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./geoip.db
          asset_name: geoip.db
          asset_content_type: application/octet-stream

      - name: Release geoip.db sha256sum
        if: steps.build.outputs.skip != 'true'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./geoip.db.sha256sum
          asset_name: geoip.db.sha256sum
          asset_content_type: text/plain

      - name: Release geoip-cn.db
        if: steps.build.outputs.skip != 'true'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./geoip-cn.db
          asset_name: geoip-cn.db
          asset_content_type: application/octet-stream

      - name: Release geoip.db sha256sum
        if: steps.build.outputs.skip != 'true'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./geoip-cn.db.sha256sum
          asset_name: geoip-cn.db.sha256sum
          asset_content_type: text/plain